---
- hosts: centos:!ppos.novelpay.pl
  serial: 1
  become: True
  tasks:
    - name: Reboot required (Red Hat) - Step 1
      command: needs-restarting -r
      register: reboot_required
      ignore_errors: True
      changed_when: False
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      tags: needsrestarting

    - name: Reboot required (Red Hat) - Step 2
      shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
      async: 30
      poll: 0
      ignore_errors: true
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and reboot_required.rc == 1

    - name: Check for reboot hint.
      shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
      ignore_errors: true
      when: ansible_os_family == 'RedHat'
      register: reboot_hint

    - name: Rebooting ...
      command: sleep 3 && shutdown -r now "Reboot required for updated kernel"
      async: 0
      poll: 0
      ignore_errors: true
      when: reboot_hint.stdout.find("reboot") != -1
      register: rebooting

    - name: Wait for thing to reboot...
      pause: seconds=45
      when: rebooting is changed

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 600
      #when: reboot is changed
