---

- hosts: artifactubuntu, novelpayubuntu
#- hosts: all
  become: yes
  gather_facts: no
  vars:
    git_user: kamilm
    git_mail: kamilm@localhost
  tasks:

    - name: check etckeeper
      command: etckeeper vcs status
      changed_when: no
      register: etckeeper
    #- debug: msg="{{ etckeeper.stdout }}"
    #- debug: msg="{{ etckeeper.stderr }}"

    - name: etckeeper check config 
      command: etckeeper vcs config --list
      changed_when: no
      register: config

    - name: git config mail
      command: etckeeper vcs config --global user.email "{{ git_mail }}"
      when: not "'mail' in config.stdout"

    - name: git config user
      command: etckeeper vcs config --global user.name "{{ git_user }}"
      when: not "'name' in config.stdout"

    - name: etckeeper add files
      command: etckeeper vcs add .
      #when: etckeeper.stdout.find("Untracked") != -1
      when: "'Untracked' in etckeeper.stdout or 'Changes not staged for commit' in etckeeper.stdout"

    - name: commit etckeeper
      command: etckeeper vcs commit -am "commit changes by ansible"
      when: "'Changes not staged for commit' in etckeeper.stdout"
