---

- hosts: artifactubuntu, novelpayubuntu
#- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: check etckeeper
      shell: etckeeper vcs status
      changed_when: no
      register: etckeeper

    - name: etckeeper add files
      shell: etckeeper vcs add .
#      when: etckeeper.stdout.find("Untracked") != -1

    - name: commit etckeeper
      shell: etckeeper vcs commit -am "commit changes by ansible"
#             when: not "'clean' in etckeeper.stdout"
