---
- hosts: miki.artifact.pl
  become: yes
  roles:
     - { role: dj-wasabi.zabbix-server, database_type: mysql, database_type_long: mysql, zabbix_server_mysql_login_user: zabbix, zabbix_server_mysql_login_password: zabbix }
     - { role: dj-wasabi.zabbix-web, database_type: mysql, database_type_long: mysql, zabbix_server_mysql_login_user: zabbix, zabbix_server_mysql_login_password: zabbix }
