- hosts: all:!edgerouter
  become: yes
  vars:
    ntp_timezone: Europe/Warsaw
  roles:
    - geerlingguy.ntp
  tasks:
    - name: install ntpstat
      package:
        name: ntpstat
      when: ansible_os_family == 'Debian'

