---
- hosts: npntms
  become: yes
  serial: 1
  gather_facts: no
  tasks:

    - name: setup
      setup: filter=ansible_os_family

    - name: is reboot needed
      stat:
        path: /var/run/reboot-required
      register: reboot
      changed_when: reboot.stat.exists
      when: ansible_os_family == 'Debian'

    - name: Reboot immediately if there was a change.
      shell: "sleep 3 && reboot"
      async: 1
      poll: 0
      when: reboot is changed

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 600
      when: reboot is changed

- hosts: npntmswildfly
  become: yes
  serial: 1
  gather_facts: no
  tasks:

    - name: wildfly restart
      service:
        name: wildfly
        state: restarted
      tags: wf
      when: reboot is changed
