- hosts: novelpay

#- name: kamil sudoers
# Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
- lineinfile:
    path: /etc/sudoers
    state: present
    #regexp: '^%wheel\s'
    line: 'kamilm ALL=(ALL) NOPASSWD: ALL'
