---
- hosts: all
#- hosts: artifactubuntu
  become: yes
  vars: 
    swap_file_size_mb: '2048'
  pre_tasks:
    - name: checking limit arg
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

  roles:
     - geerlingguy.swap

