
- hosts: ubuntu
#- hosts: virt
    
  vars: 
    admin_mail: "tadeker@onet.pl"
    
  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'
      - 'o=Ubuntu,a=${distro_codename}-updates'
      unattended_package_blacklist: [cowsay, vim]
      unattended_mail: 
