---
#- hosts: npntms, npproxmox, artiproxmox
- hosts: all:!zabbix_host
  become: yes
  vars: 
    zabbix_agent_server: 127.0.0.1,miki.artifact.pl,164.132.63.48,zabbix.novelpay.pl
    zabbix_agent_serveractive: 127.0.0.1,miki.artifact.pl,164.132.63.48,zabbix.novelpay.pl
    sign_keys: 40
    zabbix_version: 4.0
  roles:
     #- { role: dj-wasabi.zabbix-agent}
     - { role: /home/kmonti/ansible-zabbix-agent }

- hosts: zabbix_host
  become: yes
  vars: 
    zabbix_agent_server: 127.0.0.1,miki.artifact.pl,164.132.63.48
    zabbix_agent_serveractive: 127.0.0.1,miki.artifact.pl,164.132.63.48
    sign_keys: 40
    zabbix_version: 4.0
  roles:
     #- { role: dj-wasabi.zabbix-agent}
     - { role: /home/kmonti/ansible-zabbix-agent }
