---
#- hosts: npntms, npproxmox, artiproxmox
- hosts: all
  become: yes
  vars: 
    zabbix_agent_server: miki.artifact.pl,164.132.63.48
    zabbix_agent_serveractive: miki.artifact.pl,164.132.63.48
    sign_keys: 40
    zabbix_version: 4.0
  roles:
     #- { role: dj-wasabi.zabbix-agent}
     - { role: /home/kmonti/ansible-zabbix-agent }
